chore: implement boilerplate code for cliff app
canonical/cannon pull request #2
Opened 2023-06-20 07:31 UTC by mert-kirpici

2023-06-20 15:10 UTC, agileshaw requested changes
Overall LGTM. Some small suggestions inline.

2023-06-20 15:10 UTC, agileshaw commented on cannon/functional/cmd.py
> +        self.logger.info("Run called with:[%s]", parsed_args.scenario)
```suggestion
        self.logger.info("Run called with: [%s]", parsed_args.scenario)
```

2023-06-20 15:10 UTC, agileshaw commented on Makefile
>  	@echo "Cleaning snap"
Since we are creating cannon as a python package at the moment, maybe we should remove all snap-related lines? We can add them back if we ever decide to go with that route, but for now, their existence here create confusion.

2023-06-21 09:46 UTC, mert-kirpici commented on .gitignore
> +ChangeLog
during python package creation, these are created thats why i included them, they clutter the working directory

2023-06-21 09:49 UTC, mert-kirpici commented on tox.ini
> -    -r {toxinidir}/tests/unit/requirements.txt
that suggestion came from Erhan, since in the upgrader tool project, it was done the same way, we decided to follow the same approach

2023-06-22 09:56 UTC, agileshaw commented on .gitignore
> +ChangeLog
I see. In that case, I'm ok with adding them.

2023-06-22 09:57 UTC, agileshaw approved these changes

2023-06-23 10:40 UTC, rgildein commented on cannon/main.py
> +def main(argv: List[str] = sys.argv[1:]) -> int:  # pylint: disable=dangerous-default-value
Why we are using `sys.argv` as default value? I do not think that it's needed or useful

2023-06-23 10:40 UTC, rgildein commented on cannon/functional/cmd.py
> +class Run(Command):
I do not know how tempest work, but why this us needed in functional tests?

2023-06-26 20:21 UTC, closed without merging